# Generated by Django 4.1 on 2022-09-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_pedidoitem_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='moita', on_delete=django.db.models.deletion.PROTECT, to='loja.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
