# Generated by Django 4.1 on 2022-09-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='loja.cliente'),
        ),
    ]
