# Generated by Django 4.0.6 on 2022-07-29 11:22

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='phone',
        ),
        migrations.AddField(
            model_name='curso',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='image',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='foto/%y/%m/%d/', variations={'large': (800, 800), 'medium': (500, 500), 'thumbnail': (300, 300)}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
