# Generated by Django 4.0.6 on 2022-07-29 14:10

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_curso_phone_curso_description_curso_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='foto', variations={}),
        ),
    ]
